version: "3.8"

services:

    wordpress:
        depends_on: 
           - mysql
        image: wordpress
        restart: always
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - wordpress_data:/var/www/html/wp-content
        deploy:
            replicas: 1
            restart_policy:
             condition: on-failure

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_USER: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: wordpress
            ports:
        volumes:
            - mysql_data:/var/lib/mysql
        deploy:
            replicas: 1
            restart_policy:
             condition: on-failure

volumes:
    wordpress_data:
    mysql_data: